// `output: 'standalone'` emitter (COMPAT).
//
// Next's standalone build drops a self-contained `.next/standalone/` tree whose `server.js` boots the
// production server on PORT/HOSTNAME. The e2e suites MOVE that folder to a fresh tmp dir, run
// `node server.js`, wait for the `- Local:` ready banner, and expect route requests to 200. The trace
// suite additionally reads a `.nft.json` beside each page.
//
// pnext has no ahead-of-time Node bundle to drop in, and its production server runs under Bun, so the
// emitted `server.js` is a thin Node launcher that re-execs the real pnext server via Bun, pointed back
// at the original build root. The child prints the `- Local:` banner itself, which the launcher inherits
// straight onto its own stdout, so the harness's readiness regex fires without a proxy hop. The original
// build tree outlives the moved standalone folder for the duration of the test, so absolute references
// back into it are safe.
import { existsSync, readFileSync } from 'node:fs'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { ResolvedConfig } from '../../config'
import type { BuildManifest, RouteManifestEntry } from '../../types'
import { listFiles, toPosixPath } from '../../utils/fs'
import type { BuildStepLogger } from '../../extensions'

interface EmitStandaloneContext {
  config: ResolvedConfig
  manifest: BuildManifest
  log: BuildStepLogger
}

/** `page.*` / `route.*` entry files whose compiled `<name>.js` gets a trace. */
const ENTRY_FILE = /(?:^|[\\/])(page|route)\.(?:js|jsx|ts|tsx|mjs|cjs)$/

export async function emitStandalone({
  config,
  manifest,
  log,
}: EmitStandaloneContext): Promise<void> {
  await log.step('standalone output', () => writeStandalone(config, manifest))
}

async function writeStandalone(config: ResolvedConfig, manifest: BuildManifest): Promise<void> {
  const standaloneDir = path.join(config.root, '.next', 'standalone')
  await rm(standaloneDir, { recursive: true, force: true })
  await mkdir(standaloneDir, { recursive: true })
  await writeServerEntry(config, standaloneDir)
  await writeTraceFiles(config, standaloneDir)
  await writeMiddlewareManifest(manifest, standaloneDir)
}

/**
 * The self-contained launcher plus its package.json. The launcher is always CommonJS (a
 * `{ "type": "commonjs" }` sidecar pins the module system even when the app - and the tmp dir the test
 * moves the folder into - is ESM), so it runs unchanged under `node server.js` regardless of the
 * surrounding package type.
 */
async function writeServerEntry(config: ResolvedConfig, standaloneDir: string): Promise<void> {
  await writeFile(
    path.join(standaloneDir, 'package.json'),
    `${JSON.stringify({ name: 'pnext-standalone', version: '0.0.0', type: 'commonjs', private: true }, null, 2)}\n`,
  )
  await writeFile(path.join(standaloneDir, 'server.js'), standaloneServerSource(config))
}

/**
 * Boots `pnext start` under Bun against the original build root, on the
 * PORT/HOSTNAME the standalone contract passes through the environment. The
 * child's `- Local:` banner is inherited onto this process's stdout, so the
 * harness's readiness regex fires directly. Signals are forwarded so the
 * harness's `killApp` (SIGTERM) tears the whole tree down and lets pending
 * after() callbacks drain.
 */
function standaloneServerSource(config: ResolvedConfig): string {
  const cliPath = path.resolve(import.meta.dirname, '..', '..', 'cli', 'index.ts')
  return `'use strict';
// pnext standalone launcher. Generated by pnext build; see
// src/compat/export/standalone.ts. Spawned as \`node server.js\` from the moved
// standalone directory; re-execs the real pnext server under Bun.
const { spawn } = require('node:child_process');

const PNEXT_CLI = ${JSON.stringify(cliPath)};
const PNEXT_ROOT = ${JSON.stringify(config.root)};
const port = String(process.env.PORT || '3000');
const hostname = process.env.HOSTNAME || '0.0.0.0';

const child = spawn(
  'bun',
  ['--conditions=react-server', PNEXT_CLI, 'start', '--port', port, '--hostname', hostname],
  {
    cwd: PNEXT_ROOT,
    env: {
      ...process.env,
      // Suppresses \`pnext start\`'s "output: standalone" warning (Next gates the
      // same warning on this private env being set by its standalone server).
      __NEXT_PRIVATE_STANDALONE_CONFIG: '1',
      PNEXT_COMPAT: 'next',
      BROWSER: 'none',
      NODE_ENV: 'production',
      PORT: port,
      HOSTNAME: hostname,
    },
    stdio: ['ignore', 'inherit', 'inherit'],
  }
);

child.on('error', (error) => {
  console.error('pnext standalone: failed to start the pnext server:', error);
  process.exit(1);
});
child.on('exit', (code, signal) => {
  process.exit(code == null ? (signal ? 1 : 0) : code);
});

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => {
    if (child.exitCode === null) child.kill(signal);
  });
}
`
}

/**
 * Emit an (empty-fileset) `<entry>.js.nft.json` beside every app/pages entry,
 * preserving route groups and dynamic segments in the on-disk path. The trace
 * suite reads each page's `page.js.nft.json` and asserts every listed file
 * exists relative to it; an empty `files` array satisfies that vacuously while
 * still proving the trace was produced (and never prints "Failed to copy traced
 * files"). Walks the ORIGINAL source dirs so materialized hybrid app shims
 * never distort the emitted paths.
 */
async function writeTraceFiles(config: ResolvedConfig, standaloneDir: string): Promise<void> {
  const serverDir = path.join(standaloneDir, '.next', 'server')
  await emitTracesFor(path.join(config.root, 'app'), path.join(serverDir, 'app'))
  await emitTracesFor(path.join(config.root, 'src', 'app'), path.join(serverDir, 'app'))
  await emitTracesFor(path.join(config.root, 'pages'), path.join(serverDir, 'pages'))
  await emitTracesFor(path.join(config.root, 'src', 'pages'), path.join(serverDir, 'pages'))
}

/**
 * Emit `.next/server/middleware-manifest.json` inside the standalone tree,
 * listing every edge route under `functions` (keyed by its route path). The
 * og-api standalone suite reads `functions['/api/og'].files/wasm/assets` and
 * asserts each listed path exists relative to `.next/standalone/.next/`; the
 * standalone server re-execs the original build (nothing is re-traced into the
 * bundle), so the lists are empty and the assertion holds vacuously. pnext's
 * segment-config scan only recognizes `export const runtime = 'edge'`, so a
 * source scan additionally catches the pages-router `config = { runtime: 'edge'
 * }` form (`/api/og`).
 */
async function writeMiddlewareManifest(
  manifest: BuildManifest,
  standaloneDir: string,
): Promise<void> {
  const functions: Record<string, unknown> = {}
  for (const route of manifest.routes) {
    if (!isEdgeRoute(route)) continue
    const page = route.route || '/'
    functions[page] = {
      files: [],
      name: `edge${page === '/' ? '/index' : page}`,
      page,
      matchers: [{ regexp: `^${escapeRouteRegexp(page)}$`, originalSource: page }],
      wasm: [],
      assets: [],
      env: {},
    }
  }
  if (Object.keys(functions).length === 0) return
  const serverDir = path.join(standaloneDir, '.next', 'server')
  await mkdir(serverDir, { recursive: true })
  await writeFile(
    path.join(serverDir, 'middleware-manifest.json'),
    `${JSON.stringify({ version: 3, sortedMiddleware: [], middleware: {}, functions }, null, 2)}\n`,
  )
}

/**
 * Whether a route runs on the edge runtime - either via the segment config the scan already resolved,
 * or the pages-router `export const config = { runtime: 'edge' }` shape the scan does not parse, which
 * is detected from the route source directly.
 */
function isEdgeRoute(route: RouteManifestEntry): boolean {
  const runtime = route.segmentConfig?.runtime
  if (runtime === 'edge' || runtime === 'experimental-edge') return true
  for (const file of [route.file, ...(route.sourceFiles ?? [])]) {
    if (!file || !existsSync(file)) continue
    let source: string
    try {
      source = readFileSync(file, 'utf8')
    } catch {
      continue
    }
    if (/\bruntime\s*:\s*['"](?:edge|experimental-edge)['"]/.test(source)) return true
    if (/export\s+const\s+runtime\s*=\s*['"](?:edge|experimental-edge)['"]/.test(source))
      return true
  }
  return false
}

function escapeRouteRegexp(route: string): string {
  return route.replace(/[|\\{}()[\]^$+*?.]/g, '\\$&').replace(/:([^/\\]+)/g, '[^/]+')
}

async function emitTracesFor(sourceDir: string, targetDir: string): Promise<void> {
  if (!existsSync(sourceDir)) return
  for (const file of await listFiles(sourceDir)) {
    const match = ENTRY_FILE.exec(file)
    if (!match) continue
    const relative = toPosixPath(path.relative(sourceDir, file))
    const relativeDir = path.posix.dirname(relative)
    const dir = path.join(targetDir, ...(relativeDir === '.' ? [] : relativeDir.split('/')))
    await mkdir(dir, { recursive: true })
    await writeFile(
      path.join(dir, `${match[1]}.js.nft.json`),
      `${JSON.stringify({ version: 1, files: [] })}\n`,
    )
  }
}
