import { existsSync } from 'node:fs'
import { readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { ResolvedConfig } from '../config'
import { loadConfig } from '../config'
import { ensureDir, toPosixPath } from '../utils/fs'
import { scanRoutes } from '../routing/routes'
import type { RouteManifestEntry } from '../types'

export interface TypegenResult {
  file: string
  routes: number
  checks: number
  aliases: number
}

export async function typegenProject(root?: string): Promise<TypegenResult> {
  const config = await loadConfig(root)
  const routes = await scanRoutes(config.appPath)
  return writeTypegen(config, routes)
}

export async function writeTypegen(
  config: ResolvedConfig,
  allRoutes: RouteManifestEntry[],
): Promise<TypegenResult> {
  const routes = allRoutes.filter(route => !route.interception && !route.synthetic)
  const file = path.join(config.typesPath, 'pnext.gen.d.ts')
  const source = typegenSource(routes)
  await writeIfChanged(file, source)
  const aliases = await writeRouteAliases(config, routes)
  const checks = await writeChecks(config, routes)
  return { file, routes: routes.length, checks, aliases }
}

function typegenSource(routes: RouteManifestEntry[]) {
  const entries = routes.map(route => routeEntry(route)).join('\n')

  return `// This file is generated by PNext. Do not edit.
import '@wular/pnext';

declare module '@wular/pnext' {
  interface PNextRoutes {
${entries}
  }
}
`
}

function routeEntry(route: RouteManifestEntry) {
  return `    '${routeKey(route.route)}': {
      kind: '${route.kind}';
      params: ${paramsType(route)};
      mode: '${route.mode}';
      hydrated: ${route.client ? 'true' : 'false'};
    };`
}

async function writeChecks(config: ResolvedConfig, routes: RouteManifestEntry[]) {
  const checksDir = config.checksPath
  // Checks used to live under typesPath, which the app's own tsconfig includes; a stale
  // copy there fails the app's compiler on pnext internals, so heal that on every generate.
  await rm(path.join(config.typesPath, 'checks'), { recursive: true, force: true })
  await rm(checksDir, { recursive: true, force: true })
  await ensureDir(checksDir)

  // Metadata code routes (sitemap.ts, opengraph-image.tsx, ...) keep their
  // Next-style signatures, which are not PNextRouteHandlerModule shapes.
  const checked = routes.filter(route => !route.metadataRoute)
  await Promise.all(
    checked.map(route => {
      const file = path.join(checksDir, `${route.id}.check.ts`)
      return writeIfChanged(file, checkSource(checksDir, route))
    }),
  )

  return checked.length
}

async function writeRouteAliases(config: ResolvedConfig, routes: RouteManifestEntry[]) {
  const aliasesDir = path.join(config.typesPath, 'app')
  await rm(aliasesDir, { recursive: true, force: true })
  await ensureDir(aliasesDir)

  await Promise.all(
    routes.map(route => {
      const file = path.join(aliasesDir, `${routeAliasPath(config, route)}.d.ts`)
      return writeIfChanged(file, routeAliasSource(route))
    }),
  )

  return routes.length
}

function routeAliasSource(route: RouteManifestEntry) {
  const routeType = routeKey(route.route)

  return `// This file is generated by PNext. Do not edit.
import type {
  PageProps as PNextPageProps,
  RouteContext as PNextRouteContext,
  RouteParams as PNextRouteParams,
  StaticParams as PNextStaticParams,
} from '@wular/pnext';

export type Params = PNextRouteParams<'${routeType}'>;
export type PageProps = PNextPageProps<'${routeType}'>;
export type RouteContext = PNextRouteContext<'${routeType}'>;
export type StaticParams = PNextStaticParams<'${routeType}'>;
`
}

function routeAliasPath(config: ResolvedConfig, route: RouteManifestEntry) {
  const relative = toPosixPath(path.relative(config.appPath, route.file))
  const extension = path.extname(relative)
  return relative.slice(0, -extension.length)
}

function checkSource(checksDir: string, route: RouteManifestEntry) {
  const routeImport = routeImportPath(checksDir, route.file)
  const routeType = routeKey(route.route)
  const moduleType =
    route.kind === 'page'
      ? `PNextPageModule<'${routeType}'>`
      : `PNextRouteHandlerModule<'${routeType}'>`

  return `// This file is generated by PNext. Do not edit.
import type { PNextPageModule, PNextRouteHandlerModule } from '@wular/pnext/internal';
import * as routeModule from '${routeImport}';

const check: ${moduleType} = routeModule;
void check;
`
}

function routeImportPath(fromDir: string, file: string) {
  const extension = path.extname(file)
  const withoutExtension = file.slice(0, -extension.length)
  const relative = toPosixPath(path.relative(fromDir, withoutExtension))
  return relative.startsWith('.') ? relative : `./${relative}`
}

function routeKey(route: string) {
  return route.replace(/:([a-zA-Z0-9_]+)\*/g, '[...$1]').replace(/:([a-zA-Z0-9_]+)/g, '[$1]')
}

function paramsType(route: RouteManifestEntry) {
  const entries = route.params.map(param => `${JSON.stringify(param)}: string`)
  if (route.catchAll) entries.push(`${JSON.stringify(route.catchAll)}: string[]`)
  return entries.length > 0 ? `{ ${entries.join('; ')} }` : 'Record<string, never>'
}

async function writeIfChanged(file: string, source: string) {
  // A concurrent typegen (the dev server runs one off the critical path, a CLI run can overlap it
  // on the same out-dir) can delete the file between the existence check and the read; a failed
  // read just means "changed", never a crash.
  try {
    if (existsSync(file) && (await readFile(file, 'utf8')) === source) return
  } catch {
    // fall through to the write
  }
  await ensureDir(path.dirname(file))
  await writeFile(file, source)
}
