exports.PHASE_EXPORT = 'phase-export'
exports.PHASE_PRODUCTION_BUILD = 'phase-production-build'
exports.PHASE_PRODUCTION_SERVER = 'phase-production-server'
exports.PHASE_DEVELOPMENT_SERVER = 'phase-development-server'
exports.PHASE_TEST = 'phase-test'
exports.PHASE_INFO = 'phase-info'
