// Custom-server `next()` entry (COMPAT).
//
// Next apps can drive the framework through their own HTTP server, requiring 'next' and calling
// `app.prepare()` / `app.getRequestHandler()`. pnext has no `next` package to require, so `pnext build`
// materializes a minimal one into the app's `node_modules/next` when the app root ships a custom server
// entry importing 'next'.
//
// The shim's factory boots the real pnext server as a child process on an ephemeral internal port and
// proxies node req/res pairs to it, so the custom server observes Next's contract while pnext serves
// every request - basePath, server actions, after(), graceful stop included. close() SIGTERMs the child
// and awaits its exit, which lets pending after() callbacks drain.
//
// Only a missing, symlinked, or previously shimmed `node_modules/next` is replaced: the e2e harness
// links the real Next checkout for tsc typechecks, and fixtures with a genuinely installed `next` are
// left alone.
import { existsSync, lstatSync, readFileSync } from 'node:fs'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { ResolvedConfig } from '../../config'

const SERVER_ENTRY_NAMES = ['server.js', 'server.mjs', 'server.cjs', 'server.ts']
const SHIM_VERSION = '0.0.0-pnext-custom-server'

/** Whether the app root ships a custom server entry that imports 'next'. */
export function hasCustomServerEntry(root: string): boolean {
  for (const name of SERVER_ENTRY_NAMES) {
    const file = path.join(root, name)
    if (!existsSync(file)) continue
    try {
      const source = readFileSync(file, 'utf8')
      if (/(?:require\(\s*['"]next['"]\s*\)|from\s+['"]next['"])/.test(source)) return true
    } catch {
      // Unreadable entry — skip.
    }
  }
  return false
}

/**
 * Materialize the `next` custom-server shim into the app's node_modules when a
 * custom server entry exists. No-op when `node_modules/next` is a real
 * third-party install (absent, symlinked, or an earlier shim is replaced).
 */
export async function emitCustomServerShim(config: ResolvedConfig): Promise<void> {
  if (!hasCustomServerEntry(config.root)) return
  const target = path.join(config.root, 'node_modules', 'next')
  try {
    const stat = lstatSync(target)
    // A previously emitted shim is a real directory too — refresh it, so a
    // rebuild in an existing test dir never keeps a stale copy.
    if (!stat.isSymbolicLink() && !isEmittedShim(target)) return // real install — leave it alone
    await rm(target, { recursive: true, force: true })
  } catch {
    // Missing — create fresh below.
  }
  await mkdir(target, { recursive: true })
  await writeFile(
    path.join(target, 'package.json'),
    `${JSON.stringify({ name: 'next', version: SHIM_VERSION, main: 'index.cjs' }, null, 2)}\n`,
  )
  await writeFile(path.join(target, 'index.cjs'), customServerShimSource())
}

/** Whether `node_modules/next` is a shim this build emitted earlier. */
function isEmittedShim(target: string): boolean {
  try {
    const pkg = JSON.parse(readFileSync(path.join(target, 'package.json'), 'utf8')) as {
      version?: string
    }
    return pkg.version === SHIM_VERSION
  } catch {
    return false
  }
}

/**
 * The shim source. Bakes the absolute pnext CLI path so the child boots the
 * same runtime the harness/build used, from any app directory.
 */
function customServerShimSource(): string {
  const cliPath = path.resolve(import.meta.dirname, '..', '..', 'cli', 'index.ts')
  return `'use strict';
// pnext custom-server shim for require('next') / import next from 'next'.
// Generated by pnext build; see src/compat/next/custom-server.ts.
const { spawn } = require('node:child_process');

const PNEXT_CLI = ${JSON.stringify(cliPath)};
const HOP_BY_HOP = new Set([
  'connection', 'keep-alive', 'proxy-authenticate', 'proxy-authorization',
  'te', 'trailer', 'transfer-encoding', 'upgrade', 'host', 'accept-encoding',
]);

function createServer(options = {}) {
  const dev = Boolean(options.dev);
  const hostname = options.hostname || 'localhost';
  const port = options.port || 3000;
  let child;
  let childExited;
  let internalPort;

  async function prepare() {
    if (internalPort) return;
    child = spawn(
      'bun',
      ['--conditions=react-server', PNEXT_CLI, dev ? 'dev' : 'start', '--port', '0', '--hostname', '127.0.0.1'],
      {
        cwd: process.cwd(),
        env: { ...process.env, BROWSER: 'none', NODE_ENV: dev ? 'development' : 'production' },
        stdio: ['ignore', 'pipe', 'pipe'],
      }
    );
    childExited = new Promise((resolve) => child.once('exit', resolve));
    internalPort = await new Promise((resolve, reject) => {
      const timer = setTimeout(
        () => reject(new Error('pnext custom-server: timed out waiting for the pnext server to start')),
        60000
      );
      let buffer = '';
      // Echo the child's logs line by line, relabelling its "- Local: <internal>"
      // ready banner: log scanners on THIS process's stdout (the Next e2e harness
      // parses that exact line for the app URL) must not pick up the internal
      // port, or every request would bypass the custom server. Line buffering
      // keeps a coalesced/split chunk from slipping the raw banner through.
      const echoLines = (out) => {
        let tail = '';
        const write = (text) => {
          const merged = tail + text;
          const cut = merged.lastIndexOf('\\n') + 1;
          tail = merged.slice(cut);
          if (cut === 0) return;
          out.write(merged.slice(0, cut).replace(/-(\\s*)(Local|Network):/g, '[pnext internal]$1$2:'));
        };
        child.once('exit', () => { if (tail) { const rest = tail; tail = ''; out.write(rest); } });
        return write;
      };
      const echoOut = echoLines(process.stdout);
      const echoErr = echoLines(process.stderr);
      const scan = (chunk, echo) => {
        const text = chunk.toString('utf8');
        echo(text);
        if (internalPort) return;
        buffer = (buffer + text).slice(-4096);
        const match = /-\\s*Local:\\s+https?:\\/\\/[^:\\s]+:(\\d+)/.exec(buffer);
        if (match) {
          clearTimeout(timer);
          resolve(Number(match[1]));
        }
      };
      child.stdout.on('data', (chunk) => scan(chunk, echoOut));
      child.stderr.on('data', (chunk) => scan(chunk, echoErr));
      child.once('exit', (code) => {
        clearTimeout(timer);
        reject(new Error('pnext custom-server: the pnext server exited during startup (code ' + code + ')'));
      });
    });
  }

  async function handleRequest(req, res) {
    if (!internalPort) throw new Error('pnext custom-server: prepare() must complete before handling requests');
    const target = new URL(req.url || '/', 'http://127.0.0.1:' + internalPort);
    const headers = {};
    for (const [name, value] of Object.entries(req.headers)) {
      if (value === undefined || HOP_BY_HOP.has(name)) continue;
      headers[name] = Array.isArray(value) ? value.join(', ') : value;
    }
    if (req.headers.host) headers['x-forwarded-host'] = req.headers.host;
    headers['x-forwarded-proto'] = 'http';
    const method = (req.method || 'GET').toUpperCase();
    const hasBody = method !== 'GET' && method !== 'HEAD';
    const response = await fetch(target, {
      method,
      headers,
      body: hasBody ? req : undefined,
      duplex: hasBody ? 'half' : undefined,
      redirect: 'manual',
    });
    res.statusCode = response.status;
    for (const [name, value] of response.headers) {
      if (['content-encoding', 'content-length', 'transfer-encoding', 'set-cookie'].includes(name)) continue;
      if (name === 'location') {
        // Rewrite child-origin absolute redirects back to a relative target so
        // the browser stays on the custom server's host/port.
        try {
          const url = new URL(value);
          if (url.hostname === '127.0.0.1' && Number(url.port) === internalPort) {
            res.setHeader(name, url.pathname + url.search + url.hash);
            continue;
          }
        } catch {}
      }
      res.setHeader(name, value);
    }
    const setCookies = typeof response.headers.getSetCookie === 'function' ? response.headers.getSetCookie() : [];
    if (setCookies.length > 0) {
      const existing = res.getHeader('set-cookie');
      const merged = existing === undefined ? setCookies : [].concat(existing, setCookies);
      res.setHeader('set-cookie', merged);
    }
    if (response.body) {
      for await (const chunk of response.body) res.write(chunk);
    }
    res.end();
  }

  async function close() {
    if (!child || child.exitCode !== null) return;
    // Graceful: the pnext server stops accepting connections, drains pending
    // after() callbacks, then exits 0. Escalate to SIGKILL only on a hang.
    child.kill('SIGTERM');
    await Promise.race([
      childExited,
      new Promise((resolve) => setTimeout(resolve, 15000).unref()),
    ]);
    if (child.exitCode === null) child.kill('SIGKILL');
  }

  return {
    hostname,
    port,
    prepare,
    close,
    getRequestHandler: () => (req, res) => handleRequest(req, res).catch((error) => {
      console.error('pnext custom-server: request failed:', error);
      if (!res.headersSent) res.statusCode = 500;
      res.end('Internal Server Error');
    }),
    getUpgradeHandler: () => (_req, socket) => { socket.destroy(); },
    setAssetPrefix: () => {},
    logError: (...args) => console.error(...args),
    render: async (req, res) => { await handleRequest(req, res); },
    renderToHTML: async () => { throw new Error('renderToHTML is not supported by the pnext custom server'); },
  };
}

module.exports = createServer;
module.exports.default = createServer;
`
}
